README.md, bin/onelogin-aws-login, onelogin_aws_cli/__init__.py, setup.py
* Create onelogin-aws-login script
* Setup.py defaults
* Method to create and load configuration
=> Initial release

onelogin_aws_cli/__init__.py, setup.py
* Remove unnecessary event request now that API events are logged
* Change repo location
* Bump version
* Fix EU API url
=> Remove event api request

.travis.yml, setup.py
=> Add Flake8

bin/onelogin-aws-login, onelogin_aws_cli/__init__.py
Hi! I add `profile` option for (https://github.com/physera/onelogin-aws-cli/issues/16)
I changed alias to profile acording to aws cli userguide. (http://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html)
=> add profile option

onelogin_aws_cli/__init__.py
* Reset token after credentials are cached
Fixes #22
=> Reset token

onelogin_aws_cli/__init__.py, setup.py
* Enable naming profile from config
* Add expiration time to output statement
* Reset credentials after every request
=> Refresh session token

onelogin_aws_cli/__init__.py
Added code comments again to reduce the size of #39 and keep the PR focus tight.
=> Add code comments

onelogin_aws_cli/__init__.py, onelogin_aws_cli/cli.py, onelogin_aws_cli/credentials.py, onelogin_aws_cli/tests/test_configurationFile.py, onelogin_aws_cli/tests/test_oneloginAWS.py, onelogin_aws_cli/tests/test_user_choice.py, onelogin_aws_cli/userquery.py
A small PR which will address diffs in import orders when creating a PR.
=> Run autoformat over code

onelogin_aws_cli/tests/test_configurationFile.py
Code coverage was decreased by bug fix (https://github.com/physera/onelogin-aws-cli/pull/56#issuecomment-373975348). Added testcase for new functionality.
=> Add testcase for configure bug

onelogin_aws_cli/__init__.py, onelogin_aws_cli/argparse.py, onelogin_aws_cli/configuration.py, onelogin_aws_cli/credentials.py, onelogin_aws_cli/model.py
Some small changes to reduce the length of the codebase. 
Mainly turning 3 line doc blocks into 1 line doc blocks.
=> Refactor inline docs

onelogin_aws_cli/__init__.py, onelogin_aws_cli/tests/test_oneloginAWS.py, onelogin_aws_cli/tests/test_userquery.py, onelogin_aws_cli/userquery.py
Extracted user cli prompt from OneloginAWS class to be usable by daemon client.
=> Extract user role query

README.md, onelogin_aws_cli/credentials.py
Expanded the readme in regards to environment variables and the structure of the config file.
Also, compressed some doc blocks.
=> Documentation: Explain Environment Variables and config files

onelogin_aws_cli/__init__.py, onelogin_aws_cli/argparse.py, onelogin_aws_cli/tests/test_oneLoginAWSArgumentParser.py, onelogin_aws_cli/tests/test_oneloginAWS.py, onelogin_aws_cli/tests/test_oneloginAWS_saml.py
This is more or less the same content as #71 except that I've fixed the flake8 and testing issues. Don't mind how the commits get in through this PR or #71 .
=> Longer AWS Sessions

.travis.yml, onelogin_aws_cli/__init__.py, onelogin_aws_cli/cli.py, onelogin_aws_cli/credentials.py, onelogin_aws_cli/tests/test_MFACredentials.py
Given the longer `sts` sessions in #71 the motivations for #36 are no longer needed. This PR removes the interactie flags which were anticipated for a daemon
=> Remove interactive flags

onelogin_aws_cli/argparse.py, onelogin_aws_cli/tests/test_oneLoginAWSArgumentParser.py
* Just a one line change to make sure we fall back correctly.
* Accompanying test.
=> Fix defaults on argparse arguments

Pipfile, Pipfile.lock
* By using pipenv, package management can be done with python like Gemfile in ruby.
* https://github.com/pypa/pipenv
* https://docs.pipenv.org/basics/
=> by using pipenv 

README.md
=> Several fixes to README file

README.md
Several updates to readme file.
=> Several updates to readme file

setup.py
* fixup https://github.com/physera/onelogin-aws-cli/pull/123
* https://github.com/physera/onelogin-aws-cli/pull/123
=> v0.1.13 version bump

onelogin_aws_cli/configuration.py
fix typo 
thanks for this tool, really nice!
=> fix company typo
