physera/onelogin-aws-cli

onelogin_aws_cli/__init__.py

Without this fix, it seems like you just get prompted for a choice again and again even though you've input `0`:
```
$ onelogin-aws-login
Onelogin Username: mumoshu@example.com
Onelogin Password:
OTP Token: 936070
[0] arn:aws:iam::$myaccountid:role/myrole1
[1] arn:aws:iam::$myaccountid:role/myrole2
[2] arn:aws:iam::$myaccountid:role/myrole3
Role Number: 0
Role Number: 0
Role Number: 0
...
```
@physera Btw, thanks for sharing the great project 👍 Hope this helps.

Fix the bug which is preventing one from selecting the first role

---

bin/onelogin-aws-login

Hi there.
This tools is SO COOL! I was waiting for such a tool!
But, I feel hassle when I should type `--config_name` option every time to execute 'onelogin-aws-login' because we manage some AWS accounts on OneLogin.
Since I want to ease to run this command, I added `-C` option instead of `--config_name`.
Best regards.

Add long/short options for CLI

---

bin/onelogin-aws-login
onelogin_aws_cli/__init__.py

so that you no longer need to input the same username again and again, after something like
```
alias o='onelogin-aws-login -u mumoshu@example.com'
```
is configured on your shell.

Add -u / --username flag to specify an username from the command-line

---

bin/onelogin-aws-login
onelogin_aws_cli/__init__.py
setup.py

One of the challenges of working with Assumed SAML roles in AWS is that they have a 60 minute maximum timeout for all temporary credentials for these assumed roles. AWS has [committed to extending this](https://forums.aws.amazon.com/thread.jspa?threadID=178944), but have only updated the AWS console timeout (not the CLI).
To address this, I propose we support a renew option that allows for the credentials to be renewed every 59 minutes in the background.
* Add an option in script to renew credentials every 59 minutes
* Store username and password on object for renewal

Auto-renew

---

onelogin_aws_cli/__init__.py
requirements.txt
setup.py

This PR removes custom http code and simplifies the code by using the [official onelogin](https://github.com/onelogin/onelogin-python-sdk) python SDK.
This is in relation to #32 . I think the better way to go about extending the session, is rather than try to use AWS to generate longer sts session, use onelogin to re-auth. This is already being done with the `renewSeconds` option, but if MFA is enabled the user must re-enter their MFA tokens every hour. I will propose to use the refresh tokens in onelogin to have longer periods where MFA is not required. 
Using the onelogin sdk will reduce the amount of code required to do this.
Using a client library will also make generating mocks for tests significantly easier

Re-factored to use the official onelogin client

---

README.md
onelogin_aws_cli/tests/test_oneloginAWS.py

Test cases I had written weren't up to date for the onelogin client

Fix test cases to use new onelogin client

---

bin/onelogin-aws-login

I am still contemplating building a homebrew formula for `onelogin-aws-cli` as discussed in https://github.com/physera/onelogin-aws-cli/issues/41#issuecomment-366931942. This would be a flag aimed at the `test` directive in a homebrew formula.
http://www.rubydoc.info/github/Homebrew/brew/Formula.test
Eg
```ruby
test do
system "#{bin}/onelogin-aws-login”, ”--version”
end
```

Add version flag

---

bin/onelogin-aws-login
onelogin_aws_cli/cli.py
setup.py

To make testing easier, shift the cli entrypoints into functions exposed by setup and distutils.
This will also reduce the size of PR #39

Shifted bin script into setup.py endpoints

---

onelogin_aws_cli/tests/test_oneloginAWS.py

One of the test cases I wrote used `assert my_var == ...` and the test cases all use `self.assertEqual(my_var, ...)`. This PR brings that single test case into line with the others.

Use consistent testing idiosyncracies

---

.coveragerc

When running coverage tests, the test cases themselves are included at the moment.
This will exclude the test cases from coverage metrics.

Add include/exclude rules for python coverage

---

setup.py

This feels like we’re a bit further along than alpha now :-), and we do support (well... test) python 3 *only*.

Updated PyPi categories

---

.travis.yml
README.md
setup.cfg
setup.py

Modiy travis config to use nosetests to output code coverage for tests as part of build.
Eventually (if there's interest), I'd like to add https://codecov.io/ to the build process.
This can be a check in the PR, or just informative, eg https://github.com/drewsonne/terraform-provider-gocd/pull/40#issuecomment-353984463
Working demonstration of new travis configs: https://travis-ci.org/drewsonne/onelogin-aws-cli/builds/353686140

Add code coverage output to travis build

---

onelogin_aws_cli/cli.py
onelogin_aws_cli/configuration.py

If `~/.onelogin-aws.config` does not exist and `onelogin-aws-login` was called as described in the readme an error would be thrown:
```
$ onelogin-aws-login
Traceback (most recent call last):
File "/.../python-3.6.3/bin/onelogin-aws-login", line 11, in <module>
load_entry_point('onelogin-aws-cli', 'console_scripts', 'onelogin-aws-login')()
File "/.../onelogin_aws_cli/cli.py", line 40, in login
with open(DEFAULT_CONFIG_PATH, 'r+') as fp:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/.../.onelogin-aws.config'
```

Fix a bug when config file does not exist

---

setup.py

I did this initially because when testing the Arg parser, I wanted to be able to know what the package version was.
That was not necessary after using `pkg_resources`, but having a central place to change the version seemed like a good idea.
Split out of #53 to reduce its size (a bit anyway...).

Separate Version and Package Name into constants

---

onelogin_aws_cli/cli.py
onelogin_aws_cli/configuration.py

Fix a bug where the -c -C ... did not pass the config onto the initialise command.
Split out of #53 to reduce its size (a bit anyway...).

Fix bug where config name not being passed on init

---

setup.cfg

If these flags are true, then when the test cases are run to collect coverage, if there is an error they will drop into pdb mode and pause waiting for user input to control the debugger.
This causes travis to hang and breaks the build

Stop coverage.py dropping into pdb

---

onelogin_aws_cli/__init__.py
onelogin_aws_cli/configuration.py

Allow the credentials file to be specified as per standard AWS environment variables. See https://docs.aws.amazon.com/cli/latest/userguide/cli-environment.html

Allow the specification of the credentials file

---

onelogin_aws_cli/argparse.py

In order to not have to specify CLI args every time you run the program, let's add standard support for reading arguments from environment variables as well.

add support for reading arguments from environment variables

---

onelogin_aws_cli/__init__.py
onelogin_aws_cli/cli.py
onelogin_aws_cli/configuration.py
onelogin_aws_cli/credentials.py
onelogin_aws_cli/tests/test_oneloginAWS.py
onelogin_aws_cli/tests/test_oneloginAWS_saml.py
onelogin_aws_cli/tests/test_section.py

Rather than distinguishing between whether an option comes from the config file or the cli/env var's, set an order of precedence and merge all the configuration options into one resource.
This means that there is no need for separate logic to handle cli or config options in the `OneloginAWS` class.
Addresses #76

Do not distinguish between config sources

---

onelogin_aws_cli/__init__.py
onelogin_aws_cli/argparse.py
onelogin_aws_cli/configuration.py
onelogin_aws_cli/tests/test_configurationFile.py
onelogin_aws_cli/tests/test_oneLoginAWSArgumentParser.py
onelogin_aws_cli/tests/test_section.py

Not sure when this was lost. This addresses #84 .

Fixes incorrect handling of cli and config file parameter merging

---

onelogin_aws_cli/credentials.py
onelogin_aws_cli/tests/test_MFACredentials.py
onelogin_aws_cli/tests/test_userquery.py
onelogin_aws_cli/userquery.py

In preparation for being able to save prompt selections, this moves more of the prompts to use user_choice.  The function is extended to allow custom renderers, and adds the behavior we have in most prompts (e.g., automatic selection if only one option is available); this way we can kill a bunch of redundant code.
This also simplifies the way we store the current device somewhat.
Doesn't directly resolve any issues, but will handle #62 and #82 eventually.
See above
Unittests

Get all prompts to use user_choice

---

onelogin_aws_cli/cli.py
onelogin_aws_cli/configuration.py
onelogin_aws_cli/tests/test_configurationFile.py

Currently, initialised only checks if you have a non-empty non-default section.  This means that after running `-c` `is_initialised` will still return false.
The current behavior may lead to confusion if prompted to initialise their config when it's already been initialised.
New test coverage.

Initialised should return true if defaults is non-empty

---

onelogin_aws_cli/credentials.py
onelogin_aws_cli/tests/test_oneloginAWS_saml.py

Currently we unconditionally attempt to retrieve the username from the config; however we do so in a way that will throw a KeyError if the username is not actually in the config file.  This PR makes us a bit more careful.
#101 
Unittest

Handle unspecified username

---

onelogin_aws_cli/cli.py
onelogin_aws_cli/configuration.py
onelogin_aws_cli/tests/test_section.py

Currently the initialization phase takes place outside of the `with` statement which means the saving will occur on a file handle that is already closed.  This PR fixes that issue.
This PR also fixes places where we expect an "initialised" config to contain certain fields.  This introduces a `has_required` property so that we can detect janky config cases and ask them to re-run the initialization process.
Fixes #105 
Also improves error handling for #84 
Added a few unittests.
Also ran from the command line as described in the issue.

Fix config initialization

---

.editorconfig
README.md
onelogin_aws_cli/argparse.py
onelogin_aws_cli/configuration.py
onelogin_aws_cli/credentials.py
onelogin_aws_cli/tests/helper.py
onelogin_aws_cli/tests/test_configurationFile.py
onelogin_aws_cli/tests/test_oneloginAWS.py
onelogin_aws_cli/tests/test_section.py
onelogin_aws_cli/tests/test_userCredentials.py

Added a CLI option to allow the user to reset their password if stored in the OS keychain.
This change adds a cli option `--reset-password` which enables the user to clear the existing stored password, and enter a new one. If the user has specified to save the password, this functionality is respected and the new password is saved to the keychain.
The behaviour this PR fixes is described in https://github.com/physera/onelogin-aws-cli/issues/116
Users can now manage their own OS password without understanding how the password storage works.
The test cases have been modified to include a password reset case.

Allow user to reset password

---

Pipfile
Pipfile.lock
README.md
onelogin_aws_cli/__init__.py
onelogin_aws_cli/configuration.py
onelogin_aws_cli/tests/test_oneloginAWS.py
onelogin_aws_cli/tests/test_oneloginAWS_saml.py
requirements.txt
setup.py

Add support for `ip_address` and `auto_determine_ip_address` options in config file.
#111 
We use IP whitelists in OneLogin policies to say that clients coming from a certain IP don't have to provide MFA.
This is already supported in the onelogin-python-sdk, this PR just enables support for it.
1. Create an IP whitelist in a Policy in OneLogin.
2. Specify either config option in the config file.

Support for specifying client IP address, or automatically getting it from ipify

---

onelogin_aws_cli/configuration.py

If `auto_determine_ip_address` is not provided, an error `No option 'auto_determine_ip_address' in section: 'defaults'` is provided
Added a default value for `auto_determine_ip_address` in the defaults section.

auto_determine_ip_address is not a required value

---

onelogin_aws_cli/__init__.py
onelogin_aws_cli/argparse.py
onelogin_aws_cli/configuration.py
setup.py

Added region command line option to argparse.py
Added region to the REQUIRED list in configuration.py
Added region to the cred_config[name] block in __init__.py
Reference issue #125 
We have multiple accounts spanning multiple regions, so a single default region in .aws/config does not meet our needs. We set region in each entry in our .aws/credentials file to manage this. We are currently moving to use OneLogin for all our AWS accounts, and the ability to specify region is critical. Adding it to the onelogin-cli config file allows us to completely control creation of the aws credentials file with the onelogin cli. This simplifies how our development teams work.
We tested all the possible configurations (we thought of) to ensure that we didn't break existing functionality and also handled …

Add region option to command line and configuration file.

---

onelogin_aws_cli/__init__.py

AWS has multiple partitions e.g aws-cn or aws-us-gov which where previously not properly handled and cause not consistent `OneLogin` profile names.
See in addition:
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html#cfn-pseudo-param-partition
#132 
Unified `OneLogin` profile names in _~/.aws/credentials_
- Run tests with `python setup.py nosetests` 
- Logged into `China` `AWS` account with `onelogin-aws-cli` version 0.1.15
- Logged into `China` `AWS` account with updated version
- Compared the output in _~/.aws/credentials_

Fix inconsistent profile names with different AWS partitions

---

onelogin_aws_cli/__init__.py

When an AWS region is specified in the configuration file, pick them up
and override initial session with a new session with specified region.
#125 
Make `onelogin-aws-cli` working for `AWS` `China` accounts in a reliable way
- Run tests with `python setup.py nosetests`
- Logged into `China` `AWS` account with *region* configured in the configuration file
- Logged into a non `China` `AWS` account with updated version without providing *region* at all

Make sts client region aware

---

onelogin_aws_cli/__init__.py
onelogin_aws_cli/userquery.py

Fixed some pep8 violations. Ran `autopep8 -r -i onelogin_aws_cli/`
- Made sure regex is prefixed with 'r'
- Fixed long lines
- Added Missing spaces
- Blocking #120 
`flake8 .` now passes.

Fix pep8 violations

---

onelogin_aws_cli/__init__.py

When fetching saml from onelogin after providing an OTP, no errors were handled. One of the expected errors is the OTP not being valid. Now handles error responses from Onelogin and prints them to the user.
Example message returned when entering an invalid OTP:
```Exception: Onelogin Error: '401' 'Failed authentication with this factor'```
when typing an invalid otp, the error message was:
```AttributeError: 'NoneType' object has no attribute 'saml_response'```
The stack trace associated with this exception:
```
Traceback (most recent call last):
File "/usr/local/bin/onelogin-aws-login", line 11, in <module>
load_entry_point('onelogin-aws-cli==0.1.11', 'console_scripts', 'onelogin-aws-login')()
File "/usr/local/lib/python3.6/site-packages/onelogin_aws_cli/cli.py", line 65, in login
raise …
```

fix error displayed when entering invalid otp

---

Pipfile
Pipfile.lock
README.md
onelogin_aws_cli/__init__.py
requirements.txt
setup.py

Replace `ipify` with `requests` to make this project Python 3.8 compatible.
Fixes #143
`python-ipify` has been abandoned and needs to be replaced. The latest version of this dependency doesn't work with Python 3.8, so it's been replaced with a simple `requests` GET.
I've run this on Python 3.8.5 (installed via homebrew) on Mac OS Catalina 10.15.2
I use `pipenv` and the `>=3.5` string was causing an error there. Not sure how I should be representing multiple python versions as being supported, so could use some help there.

Support python 3.8 and pipenv

---

onelogin_aws_cli/tests/test_MFACredentials.py
requirements.txt

Minor change to requirements.txt to address the error.
This fixes the ModuleNotFoundError by specifying a compatible version of `onelogin` sdk package in the requirements.txt
The recent release of 3.0.0 was a breaking change:
https://github.com/onelogin/onelogin-python-sdk/releases/tag/3.0.0
https://github.com/physera/onelogin-aws-cli/issues/157
Repro steps:
In a new environment with no other python packages install onelogin-aws-cli.  Alternatively, install the requirements in a new venv as described in the README.  Observe that version 3.0.0 of onelogin is installed also.  Then, invocation of the script fails.  The nosetests also fail with similar error.
```sh
python -m pip install onelogin-aws-cli
...
pip show onelogin-aws-cli onelogin
...
Name: onelogin-aws-cli
Version: 0.1.17
... …
```

Issue 157: No module named 'onelogin.api.client
